# Generated by Django 3.0.2 on 2020-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.IntegerField(verbose_name='Rank'),
        ),
    ]
